[package]
name = "warden"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.10.0"
tokio = { version = "1.33.0", features = ["fs"] }
rfd = "0.12.1"